require:
  - rubocop-rails
  - rubocop-rspec

Style/Documentation:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/GuardClause:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - spec/**/*
RSpec/ContextWording:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
